name: deploy

on:
  push:
    branches: [ main ]

jobs:
  deploy-s3:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: lessons/03-react-basics-vite
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - run: aws s3 sync dist/ s3://${{ secrets.AWS_S3_BUCKET }} --delete
